### ISSUE TITLE
how to retrieve the access token?

### ISSUE THREAD

**Issue by jrmcdona** [Gimly/NetCoreAngularAzureB2CMsal#9] opened 2017-10-24 19:21 UTC
I am trying to fetch the accesstoken.  But I am not able to write this value out to the console?

I used your coke and trying to write out the token.  Nothing seems to get logged.

How can we get this access token for passing to other rest calls?

    public getAuthenticationToken(): Promise<string> {
        return this.clientApplication.acquireTokenSilent(environment.b2cScopes)
            .then(token => {
                console.log(token)
                return token;
            }).catch(error => {
                return this.clientApplication.acquireTokenPopup(environment.b2cScopes)
                    .then(token => {
                        console.log(token)
                        return Promise.resolve(token);
                    }).catch(innererror => {
                        console.error('Could not retrieve token from popup.', innererror);
                        return Promise.resolve('');
                    });
            });
    }

**Comment by Gimly** [comment] 2017-10-24 19:26
Hey Jordan,
On which console are you looking? This will be put in the browser console.

Do you have an error message in the console?

**Comment by jrmcdona** [comment] 2017-10-24 19:59
I am writing it out to the chrome dev tools console.     I am not able to see it, maybe because the page redirects and refreshes which clears the console?

Are you able to see the accessToken in your console log?

**Comment by Gimly** [comment] 2017-10-24 20:14
Yes, I could see the access token in the console log without any issue. There's a button in the chrome console to keep the log even when the page redirects or refreshes.

Maybe add a few breakpoints in the code to see what happens.

How are you calling the `getAuthenticationToken` method by the way?

**Comment by Gimly** [comment] 2017-10-31 15:23
Since I cannot reproduce the issue you're facing and you didn't give more information, I'm closing this issue. Feel free to reopen it with more information if you still have the issue.

**Closed as completed by Gimly** 2017-10-31 15:23 UTC
